// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"users/internal/biz"
	"users/internal/conf"
	"users/internal/data"
	"users/internal/server"
	"users/internal/service"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewMysql(confData, logger)
	client := data.NewRedis(confData, logger)
	rockscacheClient := data.NewRocksCache(confData, logger, client)
	dataData, cleanup, err := data.NewData(confData, logger, db, client, rockscacheClient)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUsersRepo(dataData, logger)
	userUsecase := biz.NewUsersUse(userRepo, logger)
	authUsecase := biz.NewAuthUse(userRepo, logger)

	userService := service.NewUsersService(userUsecase)
	authService :=  service.NewAuthService(authUsecase)
	httpServer := server.NewHTTPServer(confServer, userService, logger, authService)
	grpcServer := server.NewGRPCServer(confServer, userService, logger, authService)

	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
