// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: country/v1/country.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Country_CreateCountry_FullMethodName = "/api.country.v1.Country/CreateCountry"
	Country_UpdateCountry_FullMethodName = "/api.country.v1.Country/UpdateCountry"
	Country_DeleteCountry_FullMethodName = "/api.country.v1.Country/DeleteCountry"
	Country_GetCountry_FullMethodName    = "/api.country.v1.Country/GetCountry"
	Country_ListCountry_FullMethodName   = "/api.country.v1.Country/ListCountry"
)

// CountryClient is the client API for Country service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CountryClient interface {
	CreateCountry(ctx context.Context, in *CreateCountryRequest, opts ...grpc.CallOption) (*CreateCountryReply, error)
	UpdateCountry(ctx context.Context, in *UpdateCountryRequest, opts ...grpc.CallOption) (*UpdateCountryReply, error)
	DeleteCountry(ctx context.Context, in *DeleteCountryRequest, opts ...grpc.CallOption) (*DeleteCountryReply, error)
	GetCountry(ctx context.Context, in *GetCountryRequest, opts ...grpc.CallOption) (*GetCountryReply, error)
	ListCountry(ctx context.Context, in *ListCountryRequest, opts ...grpc.CallOption) (*ListCountryReply, error)
}

type countryClient struct {
	cc grpc.ClientConnInterface
}

func NewCountryClient(cc grpc.ClientConnInterface) CountryClient {
	return &countryClient{cc}
}

func (c *countryClient) CreateCountry(ctx context.Context, in *CreateCountryRequest, opts ...grpc.CallOption) (*CreateCountryReply, error) {
	out := new(CreateCountryReply)
	err := c.cc.Invoke(ctx, Country_CreateCountry_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *countryClient) UpdateCountry(ctx context.Context, in *UpdateCountryRequest, opts ...grpc.CallOption) (*UpdateCountryReply, error) {
	out := new(UpdateCountryReply)
	err := c.cc.Invoke(ctx, Country_UpdateCountry_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *countryClient) DeleteCountry(ctx context.Context, in *DeleteCountryRequest, opts ...grpc.CallOption) (*DeleteCountryReply, error) {
	out := new(DeleteCountryReply)
	err := c.cc.Invoke(ctx, Country_DeleteCountry_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *countryClient) GetCountry(ctx context.Context, in *GetCountryRequest, opts ...grpc.CallOption) (*GetCountryReply, error) {
	out := new(GetCountryReply)
	err := c.cc.Invoke(ctx, Country_GetCountry_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *countryClient) ListCountry(ctx context.Context, in *ListCountryRequest, opts ...grpc.CallOption) (*ListCountryReply, error) {
	out := new(ListCountryReply)
	err := c.cc.Invoke(ctx, Country_ListCountry_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CountryServer is the server API for Country service.
// All implementations must embed UnimplementedCountryServer
// for forward compatibility
type CountryServer interface {
	CreateCountry(context.Context, *CreateCountryRequest) (*CreateCountryReply, error)
	UpdateCountry(context.Context, *UpdateCountryRequest) (*UpdateCountryReply, error)
	DeleteCountry(context.Context, *DeleteCountryRequest) (*DeleteCountryReply, error)
	GetCountry(context.Context, *GetCountryRequest) (*GetCountryReply, error)
	ListCountry(context.Context, *ListCountryRequest) (*ListCountryReply, error)
	mustEmbedUnimplementedCountryServer()
}

// UnimplementedCountryServer must be embedded to have forward compatible implementations.
type UnimplementedCountryServer struct {
}

func (UnimplementedCountryServer) CreateCountry(context.Context, *CreateCountryRequest) (*CreateCountryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCountry not implemented")
}
func (UnimplementedCountryServer) UpdateCountry(context.Context, *UpdateCountryRequest) (*UpdateCountryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCountry not implemented")
}
func (UnimplementedCountryServer) DeleteCountry(context.Context, *DeleteCountryRequest) (*DeleteCountryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCountry not implemented")
}
func (UnimplementedCountryServer) GetCountry(context.Context, *GetCountryRequest) (*GetCountryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCountry not implemented")
}
func (UnimplementedCountryServer) ListCountry(context.Context, *ListCountryRequest) (*ListCountryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCountry not implemented")
}
func (UnimplementedCountryServer) mustEmbedUnimplementedCountryServer() {}

// UnsafeCountryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CountryServer will
// result in compilation errors.
type UnsafeCountryServer interface {
	mustEmbedUnimplementedCountryServer()
}

func RegisterCountryServer(s grpc.ServiceRegistrar, srv CountryServer) {
	s.RegisterService(&Country_ServiceDesc, srv)
}

func _Country_CreateCountry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCountryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CountryServer).CreateCountry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Country_CreateCountry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CountryServer).CreateCountry(ctx, req.(*CreateCountryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Country_UpdateCountry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCountryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CountryServer).UpdateCountry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Country_UpdateCountry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CountryServer).UpdateCountry(ctx, req.(*UpdateCountryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Country_DeleteCountry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCountryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CountryServer).DeleteCountry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Country_DeleteCountry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CountryServer).DeleteCountry(ctx, req.(*DeleteCountryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Country_GetCountry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCountryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CountryServer).GetCountry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Country_GetCountry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CountryServer).GetCountry(ctx, req.(*GetCountryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Country_ListCountry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCountryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CountryServer).ListCountry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Country_ListCountry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CountryServer).ListCountry(ctx, req.(*ListCountryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Country_ServiceDesc is the grpc.ServiceDesc for Country service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Country_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.country.v1.Country",
	HandlerType: (*CountryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCountry",
			Handler:    _Country_CreateCountry_Handler,
		},
		{
			MethodName: "UpdateCountry",
			Handler:    _Country_UpdateCountry_Handler,
		},
		{
			MethodName: "DeleteCountry",
			Handler:    _Country_DeleteCountry_Handler,
		},
		{
			MethodName: "GetCountry",
			Handler:    _Country_GetCountry_Handler,
		},
		{
			MethodName: "ListCountry",
			Handler:    _Country_ListCountry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "country/v1/country.proto",
}
