// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"base/internal/biz"
	"base/internal/conf"
	"base/internal/data"
	"base/internal/server"
	"base/internal/service"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewMysql(confData, logger)
	client := data.NewRedis(confData, logger)
	rockscacheClient := data.NewRocksCache(confData, logger, client)
	dataData, cleanup, err := data.NewData(confData, logger, db, client, rockscacheClient)
	if err != nil {
		return nil, nil, err
	}
	districtRepo := data.NewDistrictRepo(dataData, logger)
	greeterUsecase := biz.NewDistrictUse(districtRepo, logger)
	greeterService := service.NewDistrictService(greeterUsecase)

	rolesRepo := data.NewRolesRepo(dataData, logger)
	rolesUse := biz.NewRolesUse(rolesRepo, logger)
	rolesService := service.NewRolesService(rolesUse)

	grpcServer := server.NewGRPCServer(confServer, greeterService, logger, rolesService)
	httpServer := server.NewHTTPServer(confServer, greeterService, logger, rolesService)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
